#pragma once

enum objects { EMPTY, WALL, EXIT, PLAYER1, PLAYER2, WEB, TREASURE_S, TREASURE_B };

enum colors {
	DARKBLUE = 1, DARKGREEN = 2, DARKCYAN = 3, DARKRED = 4, DARKPINK = 5, DARKYELLOW = 6,
	GRAY = 7, BLUE = 9, GREEN = 10, CYAN = 11, RED = 12, PINK = 13, YELLOW = 14, WHITE = 15
};